---
title: "Untitled"
author: "Tian Qin"
date: '2023-11-05'
output: html_document
---
```{r}

data_p <- data.frame(dt=c("Iris","Glass","Ionosphere","Diabetes","Breast-Cancer","Balance-scale","Australian","Pima-indians","Vehicle","Raisin","Tic-tac-toe","German","Biodegradation","BHP","Diabetic","Banknote","Contraceptive","Obesity","Segments","Waveform+noise","Pendigits","Letter"),size=c(150,214,351,520,569,625,690,768,846,900,958,1000,1051,1075,1151,1372,1473,2111,2310,5000,10000,20000),acc_sbpmt=c(96.00,75.67,92.87,95.96,97.03,95.19,86.39,77.73,82.97,86.44,97.91,74.80,87.59,100,74.02,99.78,55.93,97.39,98.31,86.16,99.38,95.50),
                     acc_rf=c(94.67,77.09,93.68,97.69,96.34,83.53,87.41,76.57,75.30,86.44,99.16,76.20,87.20,100,67.95,99.34,54.16,95.03,97.79,85.36,99.21,96.85),
                    acc_xgboost=c(95.33,77.53,92.85,95.38,95.64,87.84,86.97,75.65,78.25,84.33,98.33,75.70,86.63,100,67.86,98.69,52.00,97.49,98.48,85.38,99.18,96.60),
                    num_attri=c(4,9,33,0,30,4,6,8,18,7,0,6,38,20,16,4,2,3,19,40,16,16),
                    num_cat=c(0,0,0,17,0,0,8,0,0,0,9,14,3,1,3,0,7,13,0,0,0,0))


data_p$dt = factor(data_p$dt, levels = data_p$dt)

```


### Figure 3

```{r}
library(ggplot2)
 f1<-ggplot(data_p)+
   geom_point(aes(dt,acc_sbpmt,group=1,colour="SBPMT",linetype = "SBPMT",shape="SBPMT"),size=2)+
   geom_line(aes(dt,acc_sbpmt,group=1,colour="SBPMT",linetype = "SBPMT",shape="SBPMT"),size=1) +
geom_point(aes(dt,acc_xgboost,group=1,colour="RF",linetype = "RF",shape="RF"),size=2)+
   geom_line(aes(dt,acc_xgboost,group=1,colour="RF",linetype = "RF",shape="RF"),size=1)+
geom_point(aes(dt,acc_rf,group=1,colour="XGBoost(100)",linetype = "XGBoost(100)",shape="XGBoost(100)"),size=2.5)+
   geom_line(aes(dt,acc_rf,group=1,colour="XGBoost(100)",linetype = "XGBoost(100)",shape="XGBoost(100)"),size=1)+
     scale_colour_manual("", 
                      values = c("SBPMT"="red", "RF"="blue","XGBoost(100)"="orange")) +
   scale_linetype_manual("", 
                      values = c("SBPMT"="solid", "RF"="dashed","XGBoost(100)"="twodash"))+
   scale_shape_manual("",values=c("SBPMT"=16,"RF"=17,"XGBoost(100)"=18))+
   xlab('')+
  ylab('Accuracy in %') +
   theme(text = element_text(family = "serif"))+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),panel.border  = element_rect(color = "black",fill = NA,size = 1))+
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),axis.ticks.length=unit(.25, "cm"), legend.position=c(0.9,0.25),legend.key = element_rect(colour = NA, fill = NA))



f1

```

### Figure 4

```{r}
data_p$ratio <- data_p$num_attri/( data_p$num_attri+ data_p$num_cat)
data_p2 <- data_p[order(data_p$ratio),]
data_p2$dt = factor( data_p2$dt, levels = data_p2$dt)
data_p2$dt_ratio <- paste0(data_p2$dt,' : ',round(data_p2$ratio,2))
data_p2$dt_ratio = factor( data_p2$dt_ratio, levels = data_p2$dt_ratio)
library(ggplot2)
 f2<-ggplot(data_p2)+
   geom_point(aes(dt_ratio,acc_sbpmt,group=1,colour="SBPMT",linetype = "SBPMT",shape="SBPMT"),size=2)+
   geom_line(aes(dt_ratio,acc_sbpmt,group=1,colour="SBPMT",linetype = "SBPMT",shape="SBPMT"),size=1) +
geom_point(aes(dt_ratio,acc_xgboost,group=1,colour="RF",linetype = "RF",shape="RF"),size=2)+
   geom_line(aes(dt_ratio,acc_xgboost,group=1,colour="RF",linetype = "RF",shape="RF"),size=1)+
geom_point(aes(dt_ratio,acc_rf,group=1,colour="XGBoost(100)",linetype = "XGBoost(100)",shape="XGBoost(100)"),size=2.5)+
   geom_line(aes(dt_ratio,acc_rf,group=1,colour="XGBoost(100)",linetype = "XGBoost(100)",shape="XGBoost(100)"),size=1)+
     scale_colour_manual("", 
                      values = c("SBPMT"="red", "RF"="blue","XGBoost(100)"="orange")) +
   scale_linetype_manual("", 
                      values = c("SBPMT"="solid", "RF"="dashed","XGBoost(100)"="twodash"))+
   scale_shape_manual("",values=c("SBPMT"=16,"RF"=17,"XGBoost(100)"=18))+
   xlab('')+
  ylab('Accuracy in %') +
   theme(text = element_text(family = "serif"))+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),panel.border  = element_rect(color = "black",fill = NA,size = 1))+
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),axis.ticks.length=unit(.25, "cm"), legend.position=c(0.9,0.25),legend.key = element_rect(colour = NA, fill = NA))



f2

```
