# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WoProbitBoost <- function(x_train, y_train, Wo, M_max = 50L, tol = 1e-05) {
    .Call(`_SBPMT_WoProbitBoost`, x_train, y_train, Wo, M_max, tol)
}

predictProbit <- function(x_train, tree, terminal_nodes) {
    .Call(`_SBPMT_predictProbit`, x_train, tree, terminal_nodes)
}

